/// Flutter icons ArrowIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ArrowIcons
///      fonts:
///       - asset: fonts/ArrowIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ArrowIcons {
  ArrowIcons._();

  static const _kFontFam = 'ArrowIcons';
  static const _kFontPkg = null;

  static const IconData leftArrow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightArrow = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
