/// Flutter icons BottomNavigationIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavigationIcons
///      fonts:
///       - asset: fonts/BottomNavigationIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomNavigationIcons {
  BottomNavigationIcons._();

  static const _kFontFam = 'BottomNavigationIcons';
  static const _kFontPkg = null;

  static const IconData advertise = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leads = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carSearch = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stock = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
