/// Flutter icons ErrorIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ErrorIcons
///      fonts:
///       - asset: fonts/ErrorIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ErrorIcons {
  ErrorIcons._();

  static const _kFontFam = 'ErrorIcons';
  static const _kFontPkg = null;

  static const IconData error = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noInternetConnection = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
