/// Flutter icons LoginIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LoginIcons
///      fonts:
///       - asset: fonts/LoginIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LoginIcons {
  LoginIcons._();

  static const _kFontFam = 'LoginIcons';
  static const _kFontPkg = null;

  static const IconData radioButtonNotSelected = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioButtonSelected = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passwordVisible = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switchNotChecked = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switchDisabled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switchChacked = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passwordInvisible = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
