/// Flutter icons VehicleDetailsIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VehicleDetailsIcons
///      fonts:
///       - asset: fonts/VehicleDetailsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class VehicleDetailsIcons {
  VehicleDetailsIcons._();

  static const _kFontFam = 'VehicleDetailsIcons';
  static const _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engine = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pdf = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transmission = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mileage = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reserve = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fuel = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData year = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
