/// Flutter icons VehiclesIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VehiclesIcons
///      fonts:
///       - asset: fonts/VehiclesIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class VehiclesIcons {
  VehiclesIcons._();

  static const _kFontFam = 'VehiclesIcons';
  static const _kFontPkg = null;

  static const IconData helicopter = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData van = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trailer = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_with_long_triler = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_with_short_triler = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_only_cabine = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scuter = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_sedan = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camper_van = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_trailer_big = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camper_van_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forklift = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData street_cleaner_car = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_with_two_trailers = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camp_trailer = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire_car = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_truck = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_trailer_small = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_4x4 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
